language: C
services:
  - docker

#Global variables; note this will not trigger job replication
env:
  global:
    - BUILD_DOCKER_FILE_UBUNTU_BIONIC=ci/Dockerfile-ubuntu-bionic-for-pmacct
    - BUILD_DOCKER_TAG_UBUNTU_BIONIC=ci/ubuntu-bionic-for-pmacct
    - BUILD_DOCKER_FILE_CENTOS_8_1=ci/Dockerfile-centos-8.1-for-pmacct
    - BUILD_DOCKER_TAG_CENTOS_8_1=ci/centos8.1-for-pmacct

#Matrix of jobs
jobs:
  include:

  ## User docker containers
  - docker_hub_base:
    stage: docker_hub
    name: "docker_hub: base container"
    env: PMACCT_VERSION=$(git describe --abbrev=0 --match="v*")
    script:
      - echo "Building the base container..."
      - docker build -f docker/base/Dockerfile -t pmacct_base .
      - git describe --exact-match HEAD
      - if [ $? -eq 0 ]; then \
          docker build -f docker/base/Dockerfile -t pmacct_base:latest . \
          docker build -f docker/base/Dockerfile -t pmacct_base:${PMACCT_VERSION} . \
          echo "Uploading to dockerhub ..." \
        else \
          echo "Skipping upload to dockerhub... not a release"\
        fi
