services:
  nfacctd:
    image: ${REPO:-}nfacctd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  pmacctd:
    image: ${REPO:-}pmacctd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  pmbgpd:
    image: ${REPO:-}pmbgpd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  pmbmpd:
    image: ${REPO:-}pmbmpd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  pmtelemetryd:
    image: ${REPO:-}pmtelemetryd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  sfacctd:
    image: ${REPO:-}sfacctd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure

  uacctd:
    image: ${REPO:-}uacctd:${TAG}
    volumes:
      - ./etc/pmacct:/etc/pmacct
    restart: on-failure
    privileged: true
